### ISSUE TITLE
Surface Pro 1

### ISSUE THREAD

**Issue by haymanpf** [linux-surface/acpidumps#11]
Hi there. Here is an acpidump for my Surface Pro 1. I followed an earlier example and added the txt extension so I could upload the file. 

My specs: Core i5, 4GB of memory, and 128GB SSD. 

[acpidump.out.txt](https://github.com/linux-surface/acpidumps/files/5398072/acpidump.out.txt)

Thanks for developing this!

**Comment by qzed** [comment]
Thanks! Included in cd75a2632e612bdaff6f0e94e9bc555776014dfa.

**Comment by kasperk81** [comment]
@qzed, is the list of missing device dumps up-to-date: https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#contributing-acpidumps?

**Comment by kasperk81** [comment]
maybe add Surface Pro X in the missing list :)
cc @denysvitali, if you could provide the acpidump for ProX.

**Comment by denysvitali** [comment]
This is for the Surface Pro X (SQ2)

[acpidump.zip](https://github.com/linux-surface/acpidumps/files/6371819/acpidump.zip)

**Comment by qzed** [comment]
> @qzed, is the list of missing device dumps up-to-date: https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#contributing-acpidumps?

Mostly, we now have a SL4 AMD (just updated that), but the rest is still missing (and yeah, the SPX wasn't mentioned there). You can have a look at https://github.com/linux-surface/acpidumps for all that we currently have.

@denysvitali Thanks!

**Comment by kasperk81** [comment]
@liuyishengalan, any chance you could provide acpidump from your Pro X SQ1? see https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#contributing-acpidumps
