### ISSUE TITLE
Surface Book 3 15" ACPI Dump

### ISSUE THREAD

**Issue by Universumgames** [linux-surface/acpidumps#14]
Here is my ACPI Dump from my Surface Book 3 15" with Power Base <br> [acpidump.out.txt](https://github.com/linux-surface/acpidumps/files/6101562/acpidump.out.txt)

**Comment by qzed** [comment]
Thanks! Normally ACPI code between the device variations is shared (or at least has very little differences). It looks like that's a new version though, so I've updated the SB3 code in 62972f0d806cef45ca01341e3cfbabc04c6dd583.
