### ISSUE TITLE
Surface Laptop 1

### ISSUE THREAD

**Issue by qzed** [linux-surface/acpidumps#15]
We're still missing an acpidump for the Surface Laptop 1. See https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#contributing-acpidumps for details on how to get one.

CC @ceckertz

**Comment by kasperk81** [comment]
@dcui @shemminger, I am not sure if Linux kernel supporting Surface devices is an interesting story within Microsoft, but @qzed and co. has put together a great deal of effort here in developing drivers and upstreaming kernel patches for all kinds of surface hardware. If it is possible please help acquiring acpidumps for missing models (see the link above), so eventually the quality/robustness of of surface drivers in linux kernel could improve.

**Comment by dcui** [comment]
Unluckily I don't have access to any Surface devices. :-(

**Comment by shemminger** [comment]
I will ask the internal Linux teams chat

**Comment by StollD** [comment]
I think the SL1 and SL2 use the same UEFI image. When I was working on the scripts for updating the UEFI firmware I noticed that the packages for SL1 and SL2 have the same hardware IDs (i.e. if you install the FW bundle for SL2 on SL1 it will flash the UEFI).

Based on that I would assume the acpidump of SL1 is indentical or very similar to that of SL2.

**Comment by qzed** [comment]
@StollD Thanks! I've mostly opened this issue for completeness and because I've seen that @ceckertz added themselves to the [testers](https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing) list with a SL1. So far everything on the SL1 seems to work the same way as on the SL2, so it's not a high-priority issue.

**Comment by jkbenaim** [comment]
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/6455703/acpidump.txt)

Attached is an ACPI dump from my Surface Laptop 1, model 1769.
Feel free to reach out if you need anything else from this hardware.

**Comment by qzed** [comment]
@jkbenaim Awesome, thanks!

Added in 69d5ecc1954ea5e90829b8e33541308e7451e951.

**Comment by kasperk81** [comment]
Updated wiki. Five models to go. 👍
