### ISSUE TITLE
Surface Go 3

### ISSUE THREAD

**Issue by qdeslandes** [linux-surface/acpidumps#19]
Hi,

Here is the ACPI dump for the Surface Go 3: [acpidump.txt](https://github.com/linux-surface/acpidumps/files/7315455/acpidump.txt)

Please let me know if there is anything I can help with :)

**Comment by qzed** [comment]
Thanks! Could you update the [feature matrix](https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#surface-tablets) for the Go 3? That would help quite a bit.
