### ISSUE TITLE
Surface Laptop 2

### ISSUE THREAD

**Issue by ghost** [linux-surface/acpidumps#2]
Here is a acpidump.out of my system. Laptop specifications:

Model: Surface Laptop 2
OS: Manjaro
Kernel: 5.3.18-1-surface
CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by archseer** [comment]
Added in 07a0b9d16912c53ac63a87a89d7eb57fd34b0f00, thanks!
