### ISSUE TITLE
Sruface Laptop 1  acpidump

### ISSUE THREAD

**Issue by Cryptokid92** [linux-surface/acpidumps#22]
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/9640850/acpidump.txt)

**Comment by qzed** [comment]
Thanks! We already had an acpidump for the Surface Laptop 1 but there seem to be some small differences. I've updated the one in the repo with yours in a932077491dfc6f26b9b685cd53e76bcf82183be.
