### ISSUE TITLE
ACPI dump and diagnostics for Surface Pro 9 (intel i7)

### ISSUE THREAD

**Issue by aj3423** [linux-surface/acpidumps#23]
[acpidump.txt.tar.gz](https://github.com/linux-surface/acpidumps/files/9962447/acpidump.txt.tar.gz)
[diagnostics.tar.gz](https://github.com/linux-surface/acpidumps/files/9962448/diagnostics.tar.gz)

**Comment by qzed** [comment]
Thanks! I've added the ACPI dump in 5091af939e41f0763ed9e5ff869fabea5bcc36ac.

I'll have a look at the diagnostics dump next. There should probably be a separate issue on https://github.com/linux-surface/linux-surface/ for SP9 support, so please feel free to open one. You could also have a look at updating the feature matrix at https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#surface-tablets.
