### ISSUE TITLE
Windows Dev Kit 2023 acpidump

### ISSUE THREAD

**Issue by nickdepinet** [linux-surface/acpidumps#24]
Attached the cleaned acpidump.txt from the windows dev kit 2023. Given internals of the device, probably very similar to the surface pro 9 sq3.
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/9988144/acpidump.txt)

**Comment by qzed** [comment]
Thanks! Added in e51209957f9a71e7ef3d6960f80bcbca3c4c5095.
