### ISSUE TITLE
Surface Pro 7 ACPIdump File

### ISSUE THREAD

**Issue by blockwesley** [linux-surface/acpidumps#26]
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/13328516/acpidump.txt)

**Comment by blockwesley** [comment]
I just noted a minor difference in the existing ACPI dump file for the Surface Pro 7 and my device.  The only issue I have really is that my touch display isn't working, but I haven't really done any troubleshooting on it. (also neither front nor back cameras are useful, but that item is listed as a known issue for this model) Just sharing my dump file here for others.

**Comment by qzed** [comment]
Thanks! Updated in 12160cb6ba39b8e489ff41bb0ccf26c4c06e8d6d.
