### ISSUE TITLE
Surface Pro 9 5G (1996 version) acpidump

### ISSUE THREAD

**Issue by JeromeDeBretagne** [linux-surface/acpidumps#27]
Hi @qzed,

Attached is the acpi dump of the Microsoft Surface Pro 9 5G, extracted from Windows as I didn't succeed in extracting it from my Debian partition:
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/14323332/acpidump.txt)

Thanks

**Comment by tilator** [comment]
There seems to be two versions of Surface Pro 9 5G. Is your device 1996 or 1997 version?

**Comment by JeromeDeBretagne** [comment]
> There seems to be two versions of Surface Pro 9 5G. Is your device 1996 or 1997 version?

Mine is a 1996 version.

The 2 versions should be very similar for almost all features, except the 5G radio support, according to MS doculentation:
- version 1996 supports the "regular" 5G bands under 6 GHz (5G Sub-6)
- version 1997 also supports mmWave 5G bands (in addition to 5G Sub-6) so it may have a few more antennas

I don't expect any differences in the Linux bring-up, we'll see!

**Comment by qzed** [comment]
Thanks! Added in 300dd79806bc938674dcdafcd41686bb7d183ca9.
