### ISSUE TITLE
Surface Go acpidump.out

### ISSUE THREAD

**Issue by thermes** [linux-surface/acpidumps#4]
Hi.
My Device acpidump.out is here.

Device information.
Model: Surface Go (MCZ-00032 (Japan Model))
CPU: Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz
Memory: 8GB
SSD: 128GB
Distribution: Ubuntu 19.10
Kernel: Linux 5.3.18-surface

**Comment by thermes** [comment]
[acpidump.out.txt](https://github.com/linux-surface/acpidumps/files/4108563/acpidump.out.txt)

**Comment by qzed** [comment]
Thanks!
