### ISSUE TITLE
can I use acpi patches at there to install hackintosh?

### ISSUE THREAD

**Issue by CN-Mark-Zhang** [linux-surface/acpidumps#6]
Well, I don't think this is a correct place to say this. I installed Windows & macOS & Ubuntu & Chormeos on my SP5. Now I can use a percect Ubuntu by this project, but I want to ask can I use acpi patches&drivers for hackintosh because I cannot use wifi on it. If anyone can help us for this, I will be grateful about this.

(Don't mind the incorrect place in my text, We don't speak English in our country :smile: )

**Comment by qzed** [comment]
This repository only contains dumps of the ACPI tables, and no patches to them. As far as I know, you need to do some patching to get MacOS working, but I have never done that so I can't really help you.

The drivers in this project are for Linux specifically, they won't work on MacOS (and we don't plan on supporting MacOS). You would have to write specific drivers for MacOS, as the kernel is entirely different. Again something I do not have any experience with.

I think other people have also expressed interest in support for MacOS, but I don't think anyone has tried writing those drivers yet.
